# Generated by Django 2.1.7 on 2019-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20190318_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='Prof',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
            preserve_default=False,
        ),
    ]
