# Generated by Django 2.1.7 on 2019-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Gamma',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='Sutt',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=5),
            preserve_default=False,
        ),
    ]
