# Generated by Django 2.1.7 on 2019-03-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20190318_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='Sutt',
            new_name='SUTT',
        ),
    ]
