# Generated by Django 2.1.7 on 2019-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20190318_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profundidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_P', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Gamma',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='SUTT',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Prof',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Prof',
            field=models.ManyToManyField(to='snippets.Profundidade'),
        ),
    ]
