# Generated by Django 2.1.7 on 2019-03-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20190320_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='Prof',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Prof',
            field=models.ForeignKey(default=0.5, on_delete=django.db.models.deletion.CASCADE, to='snippets.Profundidade'),
            preserve_default=False,
        ),
    ]
